blacklist: [spawn_egg, head]

permission_groups:
  test: [REDSTONE_TORCH, REDSTONE_BLOCK, REDSTONE]

messages:
  menuTitle: "Insellager"
  noPlayer: "§cDieser Befehl kann nur vom Spieler ausgeführt werden!"
  firstPage: "§aErste Seite"
  previousPage: "§aVorherige Seite"
  nextPage: "§aNächste Seite"
  lastPage: "§aLetzte Seite"
  close: "§4Schließen"
