# Mögliche Radien für die automatische Item-Sammlung (Auto-Collect).
# Der Spieler kann per Permission einen dieser Werte als Radius erhalten.
auto-collect-radius:
  - 5
  - 10
  - 20

# Liste von Item-Typen, die ausgeschlossen sind.
blacklist: [spawn_egg, head]

# Debug-Modus ein-/ausschalten (true = aktiviert, false = deaktiviert).
# Bei aktiviertem Debug werden zusätzliche Infos z.B. im Server-Log ausgegeben.
debug: false

# Definition von Permission-Gruppen mit zugehörigen Items.
permission_groups:
  test: [REDSTONE_TORCH, REDSTONE_BLOCK, REDSTONE]