blacklist: [spawn_egg, head, moving_piston]

permission_groups:
  test: [REDSTONE_TORCH, REDSTONE_BLOCK, REDSTONE]

messages:
  itemLore:
    - "&9Menge: &f%amount%"
    - ""
    - "&eLinksklick: &b%maxstacksize%x"
    - "&eRechtsklick: &b1x"
    - "&eShiftklick: &fItem direkt ins Inventar"
  menuTitle: "Dein Insellager"
  noPlayer: "§cDieser Befehl kann nur vom Spieler ausgeführt werden!"
  noPermission: "§cDu hast nicht die Berechtigung diesen Befehl zu nutzen!"
  firstPage: "§aErste Seite"
  previousPage: "§aVorherige Seite"
  nextPage: "§aNächste Seite"
  lastPage: "§aLetzte Seite"
  close: "§4Schließen"
