# Mögliche Radien für die automatische Item-Sammlung (Auto-Collect).
# Der Spieler kann per Permission einen dieser Werte als Radius erhalten.
auto-collect-radius:
  - 5
  - 10
  - 20
  -
# Debug-Modus ein-/ausschalten (true = aktiviert, false = deaktiviert).
# Bei aktiviertem Debug werden zusätzliche Infos z.B. im Server-Log ausgegeben.
debug: false

rank_blacklist:
  - banned
  - sub owner
  - mod
  - admin