name: IslandVault
version: '1.3.0-dev'
main: de.tebrox.islandVault.IslandVault
api-version: '1.21'
load: STARTUP
authors: [ Tebrox ]
description: Ein virtuelles Insellager für den OneBlock - New Life Minecraft Server

depend:
  - LuckPerms
  - BentoBox

commands:
  insellager:
    desciption: Open the player island vault
    usage: /insellager - Öffnet dein Insellager
    aliases: [lager]
    permission: islandvault.command.openGUI

  insellageradmin:
    description: adminmenu for the island vault
    usage: /insellageradmin
    aliases: [lageradmin]
    permission: islandvault.command.admin