name: IslandVault
version: '1.0.1'
main: de.tebrox.islandVault.IslandVault
api-version: '1.21'
load: STARTUP
authors: [ Tebrox ]
description: Ein virtuelles Insellager für den OneBlock - New Life Minecraft Server

commands:
  insellager:
    desciption: Open the player island vault
    usage: /insellager - Öffnet dein Insellager
    aliases: [lager]